### ISSUE TITLE
Modific hides SublimeLint mark

### ISSUE THREAD

**Issue by vferko** [gornostal/Modific#100]
In my opinion the modific mark at an edited line should have lower priority than linter, since one usually introduces lint errors by modifing a line, hence linter mark somewhat implies what modific says and has therefor more valuable information.

**Comment by gornostal** [comment]
This issue was raised here several times.
The resolution is: there is no API to set a priority to gutter marks so either you disable Modific or Linter icons, or you continue using that as you currently do.
