### ISSUE TITLE
Not working with OSX

### ISSUE THREAD

**Issue by dandaka** [gornostal/Modific#103]
OSX 10.11.6 (15G1421)
Sublime Text 3 3126
Installed Modific on 2 machines with Package Control

1. Open file
2. Save file
3. Make changes
4. Nothing happens, no visual changes on line numbers area
5. Save file
6. Nothing changes
7. Try with keys "Ctrl+Alt+D"
8. Nothings changes

I have GitGutter installed, it shows changes properly.
Other maching doesn't have GitGutter.

**Comment by gornostal** [comment]
Interesting.

Could you open the console (Ctrl+`) and look for error messages?

**Comment by dandaka** [comment]
Unable to open /Users/dandaka/Library/Application Support/Sublime Text 3/Packages/Modific/Modific.sublime-settings
Unable to open /Users/dandaka/Library/Application Support/Sublime Text 3/Packages/Modific/README.md

**Comment by gornostal** [comment]
Did you install Modific via Package Manager?
If so, could you try to reinstall it?

**Comment by dandaka** [comment]
Reinstalled
No more errors
Still not working

**Comment by gornostal** [comment]
Please try to add `"debug": false` to the Modific's user settings and look into console for any output from the plugin.
I'm wondering if it's not working because it won't start or it's a bug in the code.

**Comment by dandaka** [comment]
debug: true?

Modific: run command: git diff --no-color --no-ext-diff -- slack.html
Modific: on hl_changes: 
Modific: new lines: []
Modific: modified lines: []
Modific: deleted lines: []
Modific: run command: git diff --no-color --no-ext-diff -- slack.html
Modific: on hl_changes: 
Modific: new lines: []
Modific: modified lines: []
Modific: deleted lines: []
Modific: run command: git diff --no-color --no-ext-diff -- example.php
Modific: on hl_changes: 
Modific: new lines: []
Modific: modified lines: []
Modific: deleted lines: []

**Comment by gornostal** [comment]
Looks like there are no changes to highlight.
Try to run `git diff -- slack.html example.php` from the console.
Does it show any changes?

**Comment by dandaka** [comment]
I'm stupid. I was expecting changes since last save, not since last commit. I'm sorry and thank you for your time.

**Comment by gornostal** [comment]
no problem)
