### ISSUE TITLE
[Question] still useful since sublime text adds git support?

### ISSUE THREAD

**Issue by kud** [gornostal/Modific#107]
Hello,

Don't get me wrong, it's just a naive question but is this plugin still useful since sublime text added git support?

Seems to be redundant now, no?

<img width="324" alt="image" src="https://user-images.githubusercontent.com/655838/52066576-20054e80-2579-11e9-979f-8f565b67c25b.png">

However, I see an interest in it, it's that I can have a diff really quickly, but are there any other features which are still great?

Thank you :)

**Comment by gornostal** [comment]
hi @kud 

Thanks for raising that question. I guess people may find something in Modific that is still useful.

> I can have a diff really quickly

That's one of such things. And I like it too.
Another thing might be `replace_modified_part` command that reverts a change. `uncommitted_files` command is useful for me too.

BTW, I've just merged a PR #108 which adds an option to hide Modific's icon. Just set `region_icon` to `none` in the settings so you don't have both indicators in the gutter.

**Comment by kud** [comment]
That's lovely. Thank you @gornostal :)
