### ISSUE TITLE
SublimeText 4 support

### ISSUE THREAD

**Issue by franck-paul** [gornostal/Modific#110]
The gutter icons are not displayed with ST4 as the code only test a version beginning with 3 (line 14) and so ST4 is treated as ST2:

```python
IS_ST3 = sublime.version().startswith('3')
```

**Comment by franck-paul** [comment]
Replacing this line (14) by:

```python
IS_ST3 = sublime.version().startswith('3') or sublime.version().startswith('4')
```

Solve this issue

**Comment by gornostal** [comment]
Sorry for the late reply. I'm not planning to maintain Modific anymore.
It looks like the built-in git support is pretty good in ST now.

**Comment by franck-paul** [comment]
You're right, the built-in git support is nice in ST4 (see https://www.sublimetext.com/docs/git_integration.html).
