### ISSUE TITLE
Git show diff not opening new tab

### ISSUE THREAD

**Issue by utkonos** [gornostal/Modific#92]
I've just installed Modific and the show diff keyboard shortcut ctrl+alt+D does not open a new tab to display the diff output.

Sublime Text 3
Modific installed from Package Control
MacOS 10.10.4

**Comment by gornostal** [comment]
Do you see any errors in the console (Ctrl+`)?

I don't have OS X 10.10, but on my 10.9 inside VirtualBox Ctrl+Alt+D works fine.
Also, you can try to set a different shortcut. Let me know if that works.

**Comment by andersennl** [comment]
Same problem here. There is nothing in the console.

**Comment by gornostal** [comment]
@andersennl please provide more info (OS, Sublime version)

**Comment by gornostal** [comment]
> Also, you can try to set a different shortcut. Let me know if that works.

Have you tried this?
