### ISSUE TITLE
Sometimes no gutter update

### ISSUE THREAD

**Issue by schlamar** [gornostal/Modific#94]
Modific does sometimes no update of the gutter marks after a save. I have set `debug=true` in the configuration and I can see that Modific has actually detected the changes:

    Modific: run command: hg diff ...
    ...
    Modific: new lines: [14, 15]
    Modific: modified lines: [113, 136]
    Modific: deleted lines: [12, 117]

But it does not paint the gutter marks.

**Comment by gornostal** [comment]
@schlamar, could you provide more info?

* File before changes
* File after changes
* Your OS
* Sublime Text version

**Comment by schlamar** [comment]
Mhh, looks like it's working again. Not sure what has happened, maybe some issue with Sublime directly. I'll reopen if I'm seeing it again.
