### ISSUE TITLE
Seeks git in /usr/bin/git which triggers an error on my OSX installation

### ISSUE THREAD

**Issue by andreimoment** [gornostal/Modific#97]
Any way to change the path to git?

The correct location in my case is 

`/usr/local/bin/git`

**Comment by gornostal** [comment]
@andreimoment, Yes. It's described in README.
You can change path in `Modific -> Settings User`.

**Comment by andreimoment** [comment]
I am asking here because nothing there resembles a path. Could you please
provide an example?

**Comment by gornostal** [comment]
Here is an example.
```
{
    "vcs": [
        {"name": "git", "dir": ".git", "cmd": "/usr/local/bin/git"},
        {"name": "svn", "dir": ".svn", "cmd": "svn"},
        {"name": "bzr", "dir": ".bzr", "cmd": "bzr"},
        {"name": "hg",  "dir": ".hg",  "cmd": "hg"},
        {"name": "tf",  "dir": "$tf",  "cmd": "C:/Program Files (x86)/Microsoft Visual Studio 11.0/Common7/IDE/TF.exe"}
    ]
}
```

**Comment by andreimoment** [comment]
Thank you!

**Comment by andreimoment** [comment]
Thank you! I guess I was confused because in the main example none of the values for "cmd" looked like a path to a file... Until I noticed the Windows entry :)
