### ISSUE TITLE
SVN

### ISSUE THREAD

**Issue by mrlami** [gornostal/Modific#98]
Gutter diff colors are not showing up for SVN repos on ST3 (Mac - Yosemite)

**Comment by gornostal** [comment]
Can you look into Sublime console for any errors?

**Comment by dimon222** [comment]
Same story. No exceptions in console.

**Comment by gornostal** [comment]
@dimon222, does it reproduce with all files and all SVN repositories?
Could you be more specific in which cases Modific works and in which it does not?

**Comment by dimon222** [comment]
Yeah seem to be happening with all files.

**Comment by gornostal** [comment]
I don't have Yosemite, but I tried on Mavericks the following and I could see gutter colors:

1. `svn checkout https://github.com/gornostal/Modific`
2. `subl -n Modific`
3. Edit README.md, save it, see the gutter marks showing up.

I suggest to disable all plugins but Modific and try to reproduce the bug again.
Perhaps something else is rendering gutter after Modific.
Also you can try with GIT repository.

**Comment by aimergenge** [comment]
`'svn' ²»ÊÇÄÚ²¿»òÍâ²¿ÃüÁî£¬Ò²²»ÊÇ¿ÉÔËÐÐµÄ³ÌÐò

»òÅú´¦ÀíÎÄ¼þ¡£
`

**Comment by dimon222** [comment]
^ [Somebody ](https://github.com/SublimeText/CTags/issues/303#issuecomment-202289210) had similar problem with another plugin and got it fixed by reinstalling sublime

**Comment by ntwb** [comment]
<img width="134" alt="screen shot 2017-09-19 at 1 32 13 pm" src="https://user-images.githubusercontent.com/1016458/30574689-10dc60ce-9d3f-11e7-888f-eece67b1a4d0.png">

I just installed Modific today, the above is from an SVN repo and Modific appears to work perfectly here for me with a SVN repo

Line 25 is deleted lines and 30-32 are added lines


I'm using SVN 1.9.x so I have this Modific setting also: `svn_use_internal_diff": true`
