### ISSUE TITLE
Incompatiblity with SublimeLinter

### ISSUE THREAD

**Issue by eleretic** [gornostal/Modific#99]
Hello,

I am using both SublimeLinter and Modific, since they are a must for any workflow. The problem is, SublimeLinter is overriden by Modific. Thus, if I am modifying any file that is versionned, I won't be able to see if I have errors.

Can we get an option to make Modific not write on top of SublimeLinter in the gutter?

Thanks!

**Comment by gornostal** [comment]
I'm afraid there is no way to make SublimeLinter update gutter after Modific, or make Modific not to overwrite SublimeLinter's gutter icons.

I also use both. I set SublimeLinter to draw outlines instead of gutter (`"mark_style": "fill"`).
